---

- set_fact:
        root_drive: "{{ root_device | regex_search('[^/]+$') }}"

- name: set up encrypted drve
  block:

    - set_fact:
        drive_uuid: "{{ ansible_facts['devices'][root_drive]['links']['uuids'][0]}}"

    - name: provide default mount options
      lineinfile:
        path: /mnt/etc/default/grub
        owner: root
        group: root
        mode: 0644
        regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="
        line: "GRUB_CMDLINE_LINUX_DEFAULT=\"loglevel=3 cryptdevice=UUID={{ drive_uuid }}:MyVolGroup:allow-discards {% if usekeyfile %}cryptkey=rootfs:/crypto_keyfile.bin {%endif%}quiet\""

    - name: enable cryptdisk
      lineinfile:
        path: /mnt/etc/default/grub
        owner: root
        group: root
        mode: 0644
        regexp: "^#GRUB_ENABLE_CRYPTODISK=y"
        line: "GRUB_ENABLE_CRYPTODISK=y"

  when: encrypted_drive is succeeded
  
- name: install grub
  command: chroot /mnt grub-install --target=x86_64-efi --bootloader-id=id=grub_uefi --recheck
  register: chroot_grub_install
  changed_when: "chroot_grub_install.rc == 0"

- name: configure grub
  command: chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
  register: chroot_grub_mkconfig
  changed_when: "chroot_grub_mkconfig.rc == 0"