---
- name: gather facts - again!!
  setup:

- name: test for encrypted device
  shell:
    cmd: cryptsetup isLuks "{{root_device}}"
  register: encrypted_drive
  ignore_errors: yes

- name: Check for a keyfile
  stat:
    path: ~/crypto_keyfile.bin
  register: keyfile_result 

- set_fact:
    network_interface: "{{ ansible_default_ipv4.interface }}"
    usekeyfile: "{{ keyfile_result.stat.exists }}"

- include: locale.yml
- include: fstab.yml
- include: network.yml
- include: mkinitcpio.yml
- include: grub.yml
- include: enableservice.yml
