---
- hosts: arch

  vars_prompt:
    - name: __passphrase
      prompt: Encypted volume passphrase?
      private: no

  vars:
    __boot_device: '/dev/sdb'
    __root_device: '/dev/sda'

  roles: 
    - {role: makeboot.efi, vars: {boot_device: "{{ __boot_device }}" }}
    - {role: encryptroot, vars: {root_device: "{{ __root_device }}", passphrase: "{{ __passphrase }}"}}
    - install.arch
    - configure.arch

- name: Create Users
  import_playbook: users.yml

- name: Post Install Tasks
  import_playbook: postinstall.yml
  
  
  