---
- name: Create Volume group cryptlvm
  community.general.lvg:
    vg: MyVolGroup
    pvs: /dev/mapper/cryptlvm

- name: Create a logical volume of 4gb
  community.general.lvol:
    vg: MyVolGroup
    lv: swap
    size: 4g

- name: Create root partition
  community.general.lvol:
    vg: MyVolGroup
    lv: root
    size: +100%FREE
    shrink: no