mkinitcpio_hooks_encrypt: # Order is important
  - base
  - udev
  - autodetect
  - keyboard
  - keymap
  - consolefont
  - modconf
  - block
  - encrypt
  - lvm2
  - filesystems
  - fsck

mkinitcpio_hooks_base:
  - base
  - udev
  - autodetect
  - modconf
  - block
  - lvm2
  - filesystems
  - keyboard
  - fsck

mkinitcpio_modules_encrypt:
  - ext4

mkinitcpio_modules_base: